---
title: "R Notebook"
output: html_notebook
---



```{r}
Path="G:\\Old_drive\\Projects\\Allstate_Claim_Prediction_Challenge"
numeric_data <- read.csv(paste0(dirname(getwd()),"/data_for_models/raw_numerical.csv")) #Reading the data
head(numeric_data)

```


```{r}
y <- data.frame(Claim_Amount=numeric_data[,"Claim_Amount"])



```

```{r}
folds <- sample(1:5,nrow(numeric_data),replace = T)
nfolds <- length(unique(folds))
length(folds)
unique(folds)
```





```{r}

#i=1
library(caret)
datafiles=c("raw_numerical","svd","tsne_vars","vars_num_cor","vars1_16_PCA","Yeo_trn_vars")
prediction_folds=array(0, c(nrow(numeric_data), length(datafiles)))
prediction_full=array(0, c(nrow(numeric_data), length(datafiles)))
for(i in 1:length(datafiles)){
  print(paste0("Processing on ",datafiles[i]))
  data1 <- read.csv(paste0((dirname(getwd())),"/data_for_models/",datafiles[i],".csv"))
  if(!("Claim_Amount" %in% colnames(data1))==T)
{
  data1 <- cbind(data1,Claim_Amount=y)
  }

  
  
  
  
  
  
  # loop over folds 
  for (jj in 1:nfolds)
  {
    isTrain <- which(folds != jj)
    isValid <- which(folds == jj)
    
  Traindata<-data1[isTrain,]
  Testdata<-data1[isValid,]
  library(randomForest)
  rf1 <- randomForest(Claim_Amount~.,Traindata)
  pred <- predict(rf1,Testdata[,-ncol(Testdata)])
  
  prediction_folds[isValid,i] <- pred
  
  # predict<- cbind(Testdata,pred)
  # prediction1 <- cbind(prediction1,predict)
  }
  
  
  library(randomForest)
   rf2 <- randomForest(Claim_Amount~.,data1,mtry= (ncol(data1)/3) ,do.trace=T)
  pred_full <- predict(rf2,data1[,-ncol(data1)])
  
  prediction_full[,i] <- pred_full
  
  
  
  
  
  # control <- trainControl(method="CV", number=5,verboseIter = TRUE,savePredictions=TRUE)
  # tunegrid <- expand.grid(.mtry=c(1:15))
  # rf_model <- train(Claim_Amount ~ ., data = data1,  method="rf", metric="RMSE", tuneGrid=tunegrid, trControl=control)
  #  print(rf_model)
   
   
                           
  # pred <- predict(lm1,Testdata[,-ncol(Testdata)])
  # 
  # prediction_folds[isValid,i] <- pred
  # 
  # 
  # 
  # 
  # 
  #  lm2 <- lm(Claim_Amount~.,data1)
  # pred_full <- predict(lm2,data1[,-ncol(data1)])
  # 
  # prediction_full[,i] <- pred_full
  

}



```











```{r}
model_type="rf"
prediction_folds <- data.frame(prediction_folds)
prediction_full <- data.frame(prediction_full)
colnames(prediction_folds) <- colnames(prediction_full) <- paste(model_type, 1:ncol(prediction_full), sep = "")

prediction_folds <- cbind(prediction_folds,y)
prediction_full <-  cbind(prediction_full,y)
```




```{r}
write.csv(prediction_folds,paste0(Path,'/preds/prediction_folds_rf.csv'),row.names = F)
write.csv(prediction_full,paste0(Path,'/preds/prediction_full_rf.csv'),row.names = F)
```




```{r}
library(MLmetrics)
NormalizedGini(prediction_full$rf1,prediction_full$Claim_Amount)
NormalizedGini(prediction_full$rf2,prediction_full$Claim_Amount)
NormalizedGini(prediction_full$rf3,prediction_full$Claim_Amount)
NormalizedGini(prediction_full$rf4,prediction_full$Claim_Amount)
NormalizedGini(prediction_full$rf5,prediction_full$Claim_Amount)
NormalizedGini(prediction_full$rf6,prediction_full$Claim_Amount)

```



```{r}
normalizedGini <- function(aa, pp) {
    Gini <- function(a, p) {
        if (length(a) !=  length(p)) stop("Actual and Predicted need to be equal lengths!")
        temp.df <- data.frame(actual = a, pred = p, range=c(1:length(a)))
        temp.df <- temp.df[order(-temp.df$pred, temp.df$range),]
        population.delta <- 1 / length(a)
        total.losses <- sum(a)
        null.losses <- rep(population.delta, length(a)) # Hopefully is similar to accumulatedPopulationPercentageSum
        accum.losses <- temp.df$actual / total.losses # Hopefully is similar to accumulatedLossPercentageSum
        gini.sum <- cumsum(accum.losses - null.losses) # Not sure if this is having the same effect or not
        sum(gini.sum) / length(a)
    }
    Gini(aa,pp) / Gini(aa,aa)
}


normalizedGini(prediction_full$rf1,prediction_full$Claim_Amount)
```



```{r}
cor(prediction_full$rf1,prediction_full$Claim_Amount)
cor(prediction_full$rf2,prediction_full$Claim_Amount)
cor(prediction_full$rf3,prediction_full$Claim_Amount)
cor(prediction_full$rf4,prediction_full$Claim_Amount)
cor(prediction_full$rf5,prediction_full$Claim_Amount)
cor(prediction_full$rf6,prediction_full$Claim_Amount)
```

```{r}
MAE(prediction_full$rf1,prediction_full$Claim_Amount)
RMSE(prediction_full$rf1,prediction_full$Claim_Amount)

```








